# Generated by Django 3.2.4 on 2021-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity_app', '0002_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='type',
            field=models.CharField(choices=[('fundacja', 'fundacja'), ('organizacja pozarządowa', 'organizacja pozarządowa'), ('zbiórka lokalna', 'zbiórka lokalna')], default='fundacja', max_length=64),
        ),
    ]
